### ISSUE TITLE
The release tag is 1.30.0, but the target release according to the description and the code is 1.30.1. This breaks things.

### ISSUE THREAD

**Issue by dirkhas** [open-telemetry/opentelemetry-java-instrumentation#9525] opened 2023-09-21 07:53 UTC
Just pointing out that the release tag is 1.30.0, but the target release according to the description and the code is 1.30.1. This breaks things, for example in code that assumes that versions of all related otel libs are in sync.

**Comment by laurit** [comment] 2023-09-21 08:18
I guess the issue is that agent `1.30.0` using sdk `1.30.1`. Although `opentelemetry-java-instrumentation` and `opentelemetry-java` are closely related these projects are released separately. If an issue is discovered and fixed in the sdk before agent is released then agent will use the latest sdk patch release like in this case. If there is an issue in the agent then a new patch release will be made for the agent and sdk will not be released again. You should fix whatever it is that assumes that these 2 projects always have the same version.

**Comment by dirkhas** [comment] 2023-09-21 09:13
Ok, point taken. There is some danger in having sync'ed versions only 99% of the time -- users might think they are sync'ed 100% of the time.

**Closed** 2023-09-21 09:20 UTC

**Comment by trask** [comment] 2023-09-21 15:52
this should become clearer in the next couple of months (once HTTP semconv stabilizes) when we bump the instrumentation repo to 2.x (but the SDK / core repo will stay at 1.x)
