### ISSUE TITLE
Potential open telemetry memory leak in Spring Boot WebFlux service

### ISSUE THREAD

**Issue by zoobert** [open-telemetry/opentelemetry-java-instrumentation#8749] opened 2023-06-16 18:19 UTC
**Describe the bug**
When I instrument a very simple WebFlux Spring Boot app that simply front's a postgres database, I see a large amount of memory retained by `io.micrometer.observation.SimpleObservation` to the point where with large amounts of requests we start to receive OOM exceptions.

**Steps to reproduce**
The following is a repo containing a slimmed-down version of the problem: https://github.com/zoobert/otel-memory. This repo contains both the server with the problem and a client which makes many calls to the server to insert records.

**What did you expect to see?**
I had hoped to use open telemetry in my Spring Boot application. Micrometer cannot be eliminated from the mix because I am using both Project Reactor and Spring Security use it. I'm also using Project Reactor's automatic context propagation to get the trace context to the Reactor Context and Kotlin's coroutines.

```
Hooks.enableAutomaticContextPropagation()
```

**What did you see instead?**
Within our full application, we are running into OOM exceptions when collecting open telemetry trace spans.

**What version and what artifacts are you using?**
Artifacts: io.opentelemetry:opentelemetry-exporter-otlp,io.micrometer:micrometer-tracing-bridge-otel
Version: 1.26.0
How did you reference these artifacts? build.gradle.kts

**Environment**
Compiler: Amazon Corretto JDK 19.0.2+7-FR
OS: MacOS Ventura 13.4

**Additional context**
The problem seems to be related to r2dbc pooling, Reactor content propagation, and/or spring security. If I disable any of these the problem goes away or is diminished.

**Comment by trask** [comment] 2023-06-16 21:20
hi @zoobert! which opentelemetry-java-instrumentation dependencies (or javaagent) are you using? I couldn't find any in https://github.com/zoobert/otel-memory.

**Comment by zoobert** [comment] 2023-06-16 22:10
@trask Using the `depdencyInsight` gradle task, I can see the following dependencies are included in the `runtimeClasspath`. Most of these are pulled in by way of `org.springframework.boot:spring-boot-dependencies:3.1.0` and/or `io.micrometer:micrometer-tracing-bridge-otel:1.1.1`. The autoconfiguration is enabled because the explicit dependency on `io.opentelemetry:opentelemetry-exporter-otlp`. 

```
io.opentelemetry:opentelemetry-api:1.25.0
io.opentelemetry:opentelemetry-api:1.25.0
io.opentelemetry:opentelemetry-api-events:1.25.0-alpha
io.opentelemetry:opentelemetry-api-logs:1.25.0-alpha
io.opentelemetry:opentelemetry-context:1.25.0
io.opentelemetry:opentelemetry-exporter-common:1.25.0
io.opentelemetry:opentelemetry-exporter-common:1.25.0
io.opentelemetry:opentelemetry-exporter-otlp:1.25.0
io.opentelemetry:opentelemetry-exporter-otlp-common:1.25.0
io.opentelemetry:opentelemetry-extension-trace-propagators:1.25.0
io.opentelemetry:opentelemetry-sdk:1.25.0
io.opentelemetry:opentelemetry-sdk-common:1.25.0
io.opentelemetry:opentelemetry-sdk-extension-autoconfigure-spi:1.25.0
io.opentelemetry:opentelemetry-sdk-logs:1.25.0-alpha
io.opentelemetry:opentelemetry-sdk-metrics:1.25.0
io.opentelemetry:opentelemetry-sdk-trace:1.25.0
io.opentelemetry:opentelemetry-semconv:1.25.0-alpha
io.opentelemetry.instrumentation:opentelemetry-instrumentation-api:1.24.0
```
 
I generated this dependency report using the following:
```
$> ./gradlew :service:dependencyInsight --dependency=opentelemetry --configuration=runtimeClasspat
```

The full report is attached.
[dependencyInsight-opentelemetry.txt](https://github.com/open-telemetry/opentelemetry-java-instrumentation/files/11776455/dependencyInsight-opentelemetry.txt)

**Comment by mateuszrzeszutek** [comment] 2023-06-19 07:49
Hey @zoobert ,

It looks like your application isn't really using any of OpenTelemetry's instrumentations; it pretty much depends on the API and the instrumentation API (`io.opentelemetry.instrumentation:opentelemetry-instrumentation-api`); which is fairly battle-tested, and we're pretty certain there're no memory leaks there.

Do you have a heap dump that points to a memleak in the OpenTelemetry code?

Have you filed an issue in the Micrometer repo? It might be the `micrometer-tracing-bridge-otel` artifact that's causing the leaks, and the fact that you're noticing lots of memory occupied by `SimpleObservation` makes me think this might be a Micrometer problem -- we're not using/referencing the Micometer Observation API anywhere in our codebase.

**Comment by zoobert** [comment] 2023-06-19 14:04
@mateuszrzeszutek ,

I can cross-post over this issue in the Micrometer repo. I agree that at least part of the issue is potentially there. There are a number of open telemetry dependencies for this issue, and I started here because this is where my journey started. At work I took a stand on fully instrumenting our code with open telemetry tracing and ended up with egg on my face because our data services were hitting OOM exceptions.

The issue is complex, and I cannot seem to simplify it more than I have in this repo. It seems to be related to Micrometer. It seems to be related to Project Reactor. It seems to be related to r2dbc. It might be related to the autoconfiguration competition between Spring and Open Telemetry. It might be related to the use of Kotlin's co-routines. I fear this issue will be bounced between several projects with finger-pointing. I started here because I'd hoped you'd just tell me I have things configured incorrectly or that this is an issue someone has run into before.

If a lot of finger-pointing happens, I will likely have to strip out all of the open telemetry tracing from our services because at work I cannot get the time required to fully understand the interaction between five or six different open-source projects enough to pinpoint the problem. However, I've simplified enough I suspect it might be a common problem for any reactive data source services.

Again, I will post the issue in Micrometer's repo and see if they can provide me with some insight.

**Comment by zoobert** [comment] 2023-06-19 14:13
Cross-post: https://github.com/micrometer-metrics/micrometer/issues/3916

**Comment by izeye** [comment] 2023-06-26 10:19
https://github.com/micrometer-metrics/micrometer/issues/3916 has been closed as a duplicate of other issues that have been resolved, so it seems that this issue can be closed.

**Comment by mateuszrzeszutek** [comment] 2023-06-26 10:35
Thanks for the info @izeye !

**Closed by mateuszrzeszutek** 2023-06-26 10:35 UTC
Labels: bug
