### ISSUE TITLE
If I install another bytebuddy agent, the afterByteBuddyAgent() method would be called twice

### ISSUE THREAD

**Issue by tydhot** [open-telemetry/opentelemetry-java-instrumentation#2679] opened 2021-03-31 10:37 UTC
I had install another bytebuddy agent in my program, and I found the the method afterByteBuddyAgent() in class io.opentelemetry.instrumentation.javaagent.runtimemetrics.RuntimeMetricsInstaller would be called twice. I think it would be a metric with same name without the label added by otel agent to be exported.

**Comment by trask** [comment] 2022-06-26 04:40
hi @tydhot! there have been several changes since this, are you still able to reproduce this issue? and if so, could you post your repro to help with investigation? thx!

**Comment by trask** [comment] 2022-08-08 04:37
Closing, but please let us know if you are still seeing this issue and we will re-open, thx!

**Closed by trask** 2022-08-08 04:37 UTC
Labels: bug
