### ISSUE TITLE
2.x.x introduced errors in micrometer metrics export into GCP

### ISSUE THREAD

**Issue by AkselAllas** [open-telemetry/opentelemetry-java-instrumentation#11349] opened 2024-05-14 08:57 UTC
### Describe the bug

After upgrading to 2.3.0 from 1.3.2 we are getting the following error in GCP.

`Value type for metric [prometheus.googleapis.com/jvm_memory_committed_bytes/gauge](http://prometheus.googleapis.com/jvm_memory_committed_bytes/gauge) conflicts with the existing value type (DOUBLE)`

### Steps to reproduce

We are using `googlemanagedprometheus` exporter with no modifications

```
exporters:
  googlemanagedprometheus:
```

### Expected behavior

We don't get this error

### Actual behavior

We get this error

### Javaagent or library instrumentation version

2.3.0

### Environment

**JDK**:
**OS**:

**Comment by AkselAllas** [comment] 2024-05-14 09:22
I am trying deleting metricDescriptor via https://cloud.google.com/monitoring/api/ref_v3/rest/v3/projects.metricDescriptors/delete. 

Will see.

**Comment by AkselAllas** [comment] 2024-05-14 09:40
Didn't work.

**Comment by AkselAllas** [comment] 2024-05-14 10:05
I assume there is a certain micrometer version that 2.x.x is expecting?

**Comment by laurit** [comment] 2024-05-14 11:29
Probably the issue is that both https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/main/instrumentation/runtime-telemetry/runtime-telemetry-java8 and micrometer report a metric named `jvm.memory.committed`. Try disabling one of them and see if that resolves the issue.

**Comment by AkselAllas** [comment] 2024-05-14 11:51
@laurit 

Only dependencies of micrometer I have are:

```
"io.micrometer:micrometer-core:1.12.1"
"io.micrometer:micrometer-registry-datadog:1.12.1"
```

I removed them but error still persisted.

**Comment by AkselAllas** [comment] 2024-05-14 11:55
I will try with the following as well.

```
-Dotel.instrumentation.runtime-telemetry-java17.enable-all=false \
-Dotel.instrumentation.runtime-telemetry-java8.enable-all=false \
```

**Comment by AkselAllas** [comment] 2024-05-14 12:11
@laurit No effect on either attempt.

**Comment by AkselAllas** [comment] 2024-05-14 12:54
Still no improvement :(

**Comment by AkselAllas** [comment] 2024-05-15 08:30
@trask Any ideas?

**Comment by AkselAllas** [comment] 2024-05-15 08:53
When I remove:

```
-Dotel.instrumentation.micrometer.enabled=true
```

Then I don't get error and I don't get any metrics either.

**Comment by laurit** [comment] 2024-05-15 09:06
> I will try with the following as well.
> 
> ```
> -Dotel.instrumentation.runtime-telemetry-java17.enable-all=false \
> -Dotel.instrumentation.runtime-telemetry-java8.enable-all=false \
> ```

The name of the flag is `otel.instrumentation.runtime-telemetry.enabled`

**Closed** 2024-05-15 10:26 UTC
Labels: bug, needs triage
