### ISSUE TITLE
OpenTelemetry JAVA auto instrumentation is not exporting JVM details to Elastic.

### ISSUE THREAD

**Issue by chandru-kumar** [open-telemetry/opentelemetry-java-instrumentation#8037] opened 2023-03-12 14:53 UTC
I'm uisng opentelemetry agent to instrument the spring boot application. I built jar and attaching the agent while running the application to export the traces, metrics and logs. I can see the traces exported. But the JVM or host metrics like Heap Memory, GC, Threads, CPU , Memory etc.
java -javaagent:"C:\OpenTelemetry Demo\opentelemetry-javaagent.jar" -Dotel.resource.attributes=service.name=otel-experimental-service,service.version=1.1,deployment.environment=production -Dotel.exporter.otlp.endpoint=<elastic_apm_url> -Dotel.exporter.otlp.headers="Authorization=Bearer <elastic_secret_key>" -Dotel.metrics.exporter="otlp" -Dotel.logs.exporter="otlp" -jar todo-service-0.0.1-SNAPSHOT.jar

I expected to see the host and JVM metrics as well. But I cannot see it. Can you pls help in that to export the JVM and host details as well?

Env-
OpenJDK - 17
Otel agent - 1.23

**Comment by mateuszrzeszutek** [comment] 2023-03-13 08:00
Transferring the issue to the instrumentation repo

**Comment by mateuszrzeszutek** [comment] 2023-03-13 08:35
Duplicate of #8035

**Closed by mateuszrzeszutek** 2023-03-13 08:35 UTC
Labels: bug
