### ISSUE TITLE
Add code coverage report

### ISSUE THREAD

**Issue by kubawach** [open-telemetry/opentelemetry-java-instrumentation#1555] opened 2020-11-04 13:50 UTC
**Is your feature request related to a problem? Please describe.**
Currently there is no code coverage published for the project, therefore it's harder to spot areas where testing should be improved.

**Describe the solution you'd like**
Eg CodeCov integration, such as for https://github.com/open-telemetry/opentelemetry-java

**Describe alternatives you've considered**
None

**Additional context**
Code coverage report showing strong quality numbers should also help us in popularisation of the project

**Comment by mateuszrzeszutek** [comment] 2021-06-23 15:52
Duplicate of https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/3046; closing this one because the other issue contains more details

**Closed by mateuszrzeszutek** 2021-06-23 15:52 UTC
Labels: enhancement
