### ISSUE TITLE
Dynamic agent attach does not work for instrumentations installing filter/interceptors at app startup

### ISSUE THREAD

**Issue by pavolloffay** [open-telemetry/opentelemetry-java-instrumentation#1932] opened 2020-12-17 19:37 UTC
**Describe the bug**

First, I am not sure if this is a bug or the intended design feature.

If the javaagent is dynamically attached to an already started app some frameworks are not instrumented. For instance gRPC instrumentation hooks into `io.grpc.ServerBuilder.build()` that installs interceptor, this happens at the application startup and so if the agent is attached afterward the gRPC instrumentation will not be initialized. 

gRPC is just an example there are more instrumentations using this technique. 

**Steps to reproduce**

1. start an app using gRPC server. 
2. wait until app is running
3. attach javaagent
4. gRPC calls are not traced

**Comment by trask** [comment] 2020-12-17 23:49
oh, this is an interesting example, I hadn't thought about this limitation of dynamic attach previously, thanks for posting it.

from previous discussions, there doesn't seem to be a lot of interest in dynamic attach, can you write a little about your interest in it?

**Comment by anuraaga** [comment] 2020-12-18 03:25
Just 2c, if I had to choose between instrumenting public APIs and having less version-specific instrumentations / failing latestDepTests vs supporting dynamic attach, would favor the former. I'm presuming making these sort of scenarios dynamically instrumentable could only happen by digging into private details of the library.

**Comment by pavolloffay** [comment] 2020-12-18 06:17
> from previous discussions, there doesn't seem to be a lot of interest in dynamic attach, can you write a little about your interest in it?

we have a k8s "agent-attacher" component (daemon set) that dynamically attaches agent to the JVM. This is especially helpful when doing POCs so users don't have to rebuild their images to try out the product. All is required to deploy a single attacher.

**Comment by anuraaga** [comment] 2020-12-18 06:30
@pavolloffay Just curious if for that use case specifically, you've considered an init container with a local volume? Copies agent into volume, and can modify env var to reference that agent, so while a bit more changes in the configuration, wouldn't require rebuilding image.

**Comment by trask** [comment] 2020-12-18 06:33
+ `JAVA_TOOL_OPTIONS` env var is amazing (and not that well known/used)

**Comment by pavolloffay** [comment] 2020-12-18 06:42
@davexroth and/or @mohit-a21 could you please loop in explain why the attacher actually intercepts docker events?

**Comment by pavolloffay** [comment] 2020-12-21 14:26
@anuraaga do you know any OSS k8s operator that uses init containers and injects the agent?

**Comment by anuraaga** [comment] 2020-12-21 14:43
Some googling brought this which seems to be what we want

https://github.com/lucas-matt/auto-tracing-webhook

Not Java agent, but any service mesh like istio uses the same technique of decorating deployed pods from an admission controller I think.

It looks like app dynamics already has expertise in using init container so presumably it's just working it up to a k8s controller? :)

https://docs.appdynamics.com/display/PRO45/Install+the+Java+Agent+in+Containers#InstalltheJavaAgentinContainers-initUseInitContainers

**Comment by trask** [comment] 2020-12-21 19:19
this was a POC for injecting our javaagent into k8s via mutating webhook: https://github.com/microsoft/Application-Insights-K8s-Codeless-Attach

**Comment by iNikem** [comment] 2021-01-21 14:24
I think that when writing instrumentations the majority of developers make the assumption that agent is attached on start, not dynamically. And this assumption is backed by maintainers so far. Thus I would say this is either "design choice" or "chosen trade-off".

@pavolloffay do you think we should do something more in the context of this issue or it can be closed? Because it is definitely not a bug :)

**Comment by trask** [comment] 2021-04-04 04:02
Closing, dynamic attach is not something we plan to officially test/support. It sounds like we may accept PRs to make dynamic attach work better, but probably not at the expense of other design concerns https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/1932#issuecomment-747844517.

**Closed by trask** 2021-04-04 04:02 UTC
Labels: bug
