### ISSUE TITLE
Add supported application servers to README

### ISSUE THREAD

**Issue by breedx-splk** [open-telemetry/opentelemetry-java-instrumentation#1931] opened 2020-12-17 18:05 UTC
There is now (relatively new) support for a variety of application servers.  This support allows server spans to be created before the request ever reaches the servlet.  This is useful, because sometimes a request might have otherwise been rejected or filtered and wouldn't have reached the servlet instrumentation.

Users who are running various application servers might check in with the OpenTelemetry java instrumentation README [https://github.com/open-telemetry/opentelemetry-java-instrumentation#supported-java-libraries-and-frameworks](to see if their framework/server is supported)...but these servers have not yet been added.

So this issue is to ask for the supported application servers to be added to [the supported list](https://github.com/open-telemetry/opentelemetry-java-instrumentation#supported-java-libraries-and-frameworks) in the README.

**Comment by vovencij** [comment] 2020-12-18 08:54
Is this a duplicate of https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/1076 ?

**Comment by iNikem** [comment] 2020-12-18 09:08
Indeed it is. Sorry @breedx-splk for this extra work :(

**Closed by iNikem** 2020-12-18 09:08 UTC
Labels: enhancement

**Comment by breedx-splk** [comment] 2020-12-18 17:27
Oh yeah good catch @vovencij !  Thanks!
