### ISSUE TITLE
SQL Query Parameters Not Captured in OpenTelemetry Java Agent

### ISSUE THREAD

**Issue by sstglobal** [open-telemetry/opentelemetry-java-instrumentation#11724] opened 2024-07-02 14:57 UTC
### Describe the bug

SQL query parameters are not being captured when using the OpenTelemetry Java agent version 2.4.0 with Spring Boot and Hibernate.

### Steps to Reproduce
1. Set up a Spring Boot application with the following dependencies:
    - `spring-boot-starter-data-jpa`
    - `oracle-ojdbc8`
    - `opentelemetry-javaagent`

2. Configure the application properties:
    ```properties
    spring.datasource.jndi-name=jdbc/test
    spring.jpa.database-platform=org.hibernate.dialect.Oracle12cDialect
    spring.jpa.show-sql=true
    spring.jpa.properties.hibernate.format_sql=true
    logging.level.org.hibernate.SQL=DEBUG
    logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
    ```

3. Start the application with the OpenTelemetry Java agent:
    ```sh
    java -javaagent:/path/to/opentelemetry-javaagent.jar \
         -Dotel.exporter.otlp.endpoint=http://tempo:4317 \
         -Dotel.service.name=dev \
         -Dotel.exporter.otlp.protocol=grpc \
         -Dotel.instrumentation.jdbc.capture-parameters=true \
         -Dotel.javaagent.debug=true \
         -jar your-application.jar
    ```

4. Execute a SQL query using JPA.

### Expected behavior

SQL query parameters should be captured and logged in Tempo.

### Actual behavior

SQL query parameters are not being captured.

### Javaagent or library instrumentation version

2.4.0

### Environment

- OS: Ubuntu 20.04
- Spring Boot version: 2.4.x
- Hibernate version: 5.x
- Oracle JDBC Driver version: ojdbc8

**Comment by laurit** [comment] 2024-07-05 12:35
Duplicate of https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/7413

**Closed** 2024-07-05 12:36 UTC
Labels: bug, needs triage

**Comment by sstglobal** [comment] 2024-07-10 04:08
This issue is not resolved when hosting the application on Oracle WebLogic Server.

**Comment by laurit** [comment] 2024-07-10 06:41
> This issue is not resolved when hosting the application on Oracle WebLogic Server.

@sstglobal this issue is duplicate of issue #7413
