### ISSUE TITLE
opentelemetry and cassandra

### ISSUE THREAD

**Issue by DinaYakovlev** [open-telemetry/opentelemetry-java-instrumentation#2078] opened 2021-01-19 11:27 UTC
Hi, I am trying to integrate the opentelemetry-instrumentation to a scala project I have.
We are using jaeger as our tracing tool.
The problem is, we are using com.datastax.cassandra cassandra-driver-core version 3.1.0 in this projefct, that uses guava dependency version 16.0.1.
Unfortunately we can not upgrade the cassandra-driver-core as a result of other dependencies..
did anyone ever encountered a similar issue, or have any idea how we can overcome this problem, without upgrading the cassandra driver?

**Comment by iNikem** [comment] 2021-01-19 11:30
Do you have any specific problem with OpenTelemetry javaagent? If yes, please provide more information about what does not work for you.

**Comment by DinaYakovlev** [comment] 2021-01-19 11:41
Well, at startup we get:
```
Error creating bean with name 'otelRestTemplateBeanPostProcessor' defined in class path resource 
[io/opentelemetry/instrumentation/spring/autoconfigure/httpclients/resttemplate/RestTemplateAutoConfiguration.class]: 
Unsatisfied dependency expressed through method 'otelRestTemplateBeanPostProcessor' parameter 0; nested exception is 
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'otelTracer' defined in class path resource [io/opentelemetry/instrumentation/spring/autoconfigure/TracerAutoConfiguration.class]: 
Bean instantiation via factory method failed; 
nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [io.opentelemetry.api.trace.Tracer]: Factory method 'otelTracer' threw exception; 
nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'otelJaegerSpanExporter' defined in class path resource
[io/opentelemetry/instrumentation/spring/autoconfigure/exporters/jaeger/JaegerSpanExporterAutoConfiguration.class]: 
Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException:
Failed to instantiate [io.opentelemetry.exporter.jaeger.JaegerGrpcSpanExporter]: Factory method 'otelJaegerSpanExporter'
threw exception; nested exception is java.lang.NoSuchMethodError:
com.google.common.base.Preconditions.checkArgument(ZLjava/lang/String;CLjava/lang/Object
```

And this:
```
The method's class, com.google.common.base.Preconditions, is available from the following locations:
jar:file:/Users/myUser/.m2/repository/com/google/guava/guava/16.0.1/guava-16.0.1.jar!/com/google/common/base/Preconditions.class
```
Excluding guava from cassandra-driver-core is not an option...

**Comment by iNikem** [comment] 2021-01-19 11:58
Thanks, that clarifies things! :)

**Comment by shyimo** [comment] 2021-01-27 13:17
Hi @iNikem !
We are having the same problem 
any expected date for a fix ?

**Comment by iNikem** [comment] 2021-01-27 16:22
Right now we lack the easily reproducible test case for this. And we put main effort into getting 1.0 out of the door.

So no committed day yet :(

**Comment by trask** [comment] 2021-01-27 17:58
@DinaYakovlev @shyimo can you post a repro for this (e.g. a github repository that we can build, run, and reproduce the issue)?

**Comment by DinaYakovlev** [comment] 2021-01-28 14:41
@trask unfortunately I can't, this is happening to me in a company project that is in a private repository

**Comment by trask** [comment] 2021-04-06 04:04
@DinaYakovlev @shyimo are you still having this issue? from the exception above, it looks like you are trying to use the `spring-boot-autoconfigure` project, and it looks like you are pulling in the jaeger exporter:

```
Factory method 'otelJaegerSpanExporter'
threw exception; nested exception is java.lang.NoSuchMethodError:
com.google.common.base.Preconditions.checkArgument(ZLjava/lang/String;CLjava/lang/Object
```

The jaeger exporter relies on grpc, which relies on a more recent version of guava, which would explain where your conflict is coming from.

If you stick to the pure OpenTelemetry javaagent (+ OpenTelemetry API), then you won't pull in grpc onto your application classpath. The OpenTelemetry javaagent has jaeger exporter embedded, but in a different class loader so that it won't cause any conflicts with your application dependencies.

**Comment by trask** [comment] 2021-05-09 04:30
Closing, but please let us know if you are still having this issue and we will re-open.

**Closed by trask** 2021-05-09 04:30 UTC
Labels: bug
