### ISSUE TITLE
Update list of instrumentation IDs

### ISSUE THREAD

**Issue by kubawach** [open-telemetry/opentelemetry-java-instrumentation#2701] opened 2021-04-02 13:27 UTC
**Is your feature request related to a problem? Please describe.**

List of instrumentation IDs (https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/docs/suppressing-instrumentation.md) should be populated.

**Comment by mateuszrzeszutek** [comment] 2021-04-02 13:44
Duplicate of #2256

**Closed by mateuszrzeszutek** 2021-04-02 13:44 UTC
Labels: documentation, enhancement

**Comment by kubawach** [comment] 2021-04-02 17:49
Searched for a duplicate before submitting, didn't find, used wrong tokens for search :D
