### ISSUE TITLE
Spring Boot WebFlux + open-telemetry java agent, use Baggage and makeCurrent() in Filter, traceId is duplicated for many times. 

### ISSUE THREAD

**Issue by giantoneday** [open-telemetry/opentelemetry-java-instrumentation#12089] opened 2024-08-22 14:43 UTC
Hi, 
I use Spring Boot  WebFlux + open-telemetry java agent,  and add Baggage to the Context,  but I found that if I add baggage.storeInContext(Context.current()).makeCurrent() on Filter, 
1. Call a normal block http api,  everything is fine.
2. Call a flux http api,  each traceId is  duplicated for many times. 
3. If I don't add baggage to Context and don't makeCurrent(), then flux api is also fine.

My test project is here: [flux-open-telemetry.zip](https://github.com/user-attachments/files/16713511/flux-open-telemetry.zip)

And please read the README to reproduce my issue. 
Could you please show me how to fix this problem?  Because it's important for me. 

# some similar issues reported by others:
1. https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/8125
2. https://github.com/open-telemetry/opentelemetry-java-instrumentation/discussions/3168
3. https://github.com/open-telemetry/opentelemetry-java/issues/1531

Thanks.

**Comment by laurit** [comment] 2024-08-23 11:02
Duplicate of https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/12085

**Closed** 2024-08-23 11:02 UTC
Labels: bug
