### ISSUE TITLE
Does OpenTelemetry support auto instrumentation for https://spring.io/projects/spring-cloud-gateway

### ISSUE THREAD

**Issue by rajankamdi0706** [open-telemetry/opentelemetry-java-instrumentation#9125] opened 2023-08-02 04:57 UTC
**Is your feature request related to a problem? Please describe.**
No, wanted to know if open telemetry support for auto instrumentation of spring-cloud-gateway

**Comment by mateuszrzeszutek** [comment] 2023-08-03 09:47
Duplicate of #9121

**Closed by mateuszrzeszutek** 2023-08-03 09:47 UTC
Labels: Feature Request
