### ISSUE TITLE
why not support java nio

### ISSUE THREAD

**Issue by LUAgam** [open-telemetry/opentelemetry-java-instrumentation#2505] opened 2021-03-05 02:51 UTC
i want to use open-telemetry on a system that implements network switching based on java nio? Is it supported now? If you don’t support it, what are the feasible solutions?

**Comment by trask** [comment] 2021-04-06 01:37
Closing as duplicate of #1311.

@LUAgam [manual instrumentation](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/docs/manual-instrumentation.md) is a decent option for now

**Closed by trask** 2021-04-06 01:37 UTC
Labels: enhancement
