### ISSUE TITLE
Propagate span-context for Kafka Clients by injecting and extracting in kafka connect headers

### ISSUE THREAD

**Issue by radzikp** [open-telemetry/opentelemetry-java-instrumentation#2801] opened 2021-04-14 08:30 UTC
Hi 

Kafka connect: Confluent Platform 5.5.0
Kafka version: 5.5.0-ccs (Kafka 2.5.0)
Opentelemetry agent attached v1.0.1 (kafka clients 0.11 1.0.1)

I have an issue to propagate a trace context from kafka connect headers to kafka headers.

Here is a log: 

[opentelemetry.auto.trace 2021-04-14 08:03:46:510 +0000] [task-thread-my-application-pre-prod-0] INFO io.opentelemetry.exporter.logging.LoggingSpanExporter - '**my-manual-created-span**' : **fbc62ae5f20fa2da33c648a4fdaf3712** c44255b3ff734da4 INTERNAL [tracer: my-app-telemetry:1.0.1] AttributesMap{data={thread.id=102, thread.name=task-thread-myapp-pre-prod-0}, capacity=128, totalAddedValues=2}

_--here: my custom logic to get context and put to connect headers_
[2021-04-14 08:03:46,510] INFO ActivateTracingSpan - record headers '**ConnectHeaders**(headers=[ConnectHeader(key=traceparent, value=00-**fbc62ae5f20fa2da33c648a4fdaf3712**-e6ad44cfa70ea248-01, schema=Schema{STRING})])' (com.package.ActivateTracingSpan)

_--different traceid (generated by java agent)_
[opentelemetry.auto.trace 2021-04-14 08:03:46:526 +0000] [kafka-producer-network-thread | connector-producer-my-app-pre-prod-0] INFO io.opentelemetry.exporter.logging.LoggingSpanExporter - '**pre-prod.TOPIC_NAME send**' : **_6a07cd7ed8a6a56c6a0d326344dc49d6_** 868ec70b4d066605 PRODUCER [tracer: io.opentelemetry.javaagent.kafka-clients-0.11:1.0.1] AttributesMap{data={messaging.system=kafka, thread.id=102, messaging.destination_kind=topic, thread.name=task-thread-my-application-pre-prod-0, messaging.destination=pre-prod.TOPIC_NAME}, capacity=128, totalAddedValues=5}

It looks like the issue is related between kafka connect and kafka when kafka connect creating a kafka message. It seems like not adding headers....

Any ideas why context is not propagated from kafka connect custom transformation - ActiaveTracingSpan  to kafka message header ? 

My issue is related to #1113

**Comment by radzikp** [comment] 2021-04-14 13:16
Additional comment:
I figured out that kafka headers are overriden by java agent when message are being produced.

**Comment by iNikem** [comment] 2021-04-15 07:07
> So if tracespan/traceid is present on kafka message header why java agent overrides it ?

This question is easy to answer: because java agent currently assumes that only it is responsible for context propagation and thus does not check if some context is already propagated.

But I think more interesting questions are: 

- Why do you want to propagate context manually?
- Why your manual context has different traceId from the one managed/propagated by the javaagent?

Can you tell us more about your use-case of manual propagation?

**Comment by radzikp** [comment] 2021-04-15 07:24
> Why do you want to propagate context manually?
I am using kafka connect / outbox pattern in my solution.

> Can you tell us more about your use-case of manual propagation?
1. Outbox pattern - jdbc connector reads serialized context from db table. 
2. Manual span is created from serialized context.
3. Kafka connector header is created and context is being propagated to kafka messages by kafka connect - record.
4. Record is transformed to kafka message by kafka connect producer.

**Comment by iNikem** [comment] 2021-04-15 09:03
> 2\. Manual span is created from serialized context.

When you care your span manually, do you create a scope for this new span using `span.makeCurrent()` as demonstrated [here](https://opentelemetry.io/docs/java/manual_instrumentation/#create-a-basic-span)?

**Comment by radzikp** [comment] 2021-04-15 13:05
> When you care your span manually, do you create a scope for this new span using span.makeCurrent() as demonstrated here?

Yes. I tried couple of different ways of creating spans but I do the way you / docs describes.

**Comment by iNikem** [comment] 2021-04-16 06:20
Can you create a small reproducible example to demonstrate this problem? This would really speed up the investigation :)

**Comment by trask** [comment] 2022-06-26 04:39
Closing, there have been several kafka instrumentation fixes since this, if you are still seeing the issue with the latest javaagent version, let us know and we'll reopen.

**Closed by trask** 2022-06-26 04:39 UTC
Labels: bug

**Comment by vidourem** [comment] 2023-02-16 19:15
Hi,

I am trying to do the exact same thing and I am facing the same issue with the latest version of the Java agent. To work around the problem, I have created an Interceptor that extends the Kafka interceptor provided by OpenTelemetry to retrieve the context of the ProducerRecord and make it the current context. To make this work, automatic Kafka instrumentation must also be disabled.
