### ISSUE TITLE
Add propagation control to ClientInstrumenter.

### ISSUE THREAD

**Issue by zmapleshine** [open-telemetry/opentelemetry-java-instrumentation#3615] opened 2021-07-19 02:34 UTC
**Is your feature request related to a problem? Please describe.**

Hi all. I am viewing the general instrument behavior of the client span, and I found that the context is unconditionally propagated downstream in the ``ClientInstrumenter``. 

This is not a good setting for MQ. More often than not, the message producer will not propagate the current context information to downstream.

**Describe the solution you'd like**
Add a field to ``ClientInstumenter`` to control the propagation behavior, as described in the title,the default value is "true".

**Describe alternatives you've considered**
Or , add a new Instrumenter named "MessageProducerInstrumenter" as MQ type of instrument.

**Additional context**

In the full-link stress test scenario, the message producer needs to pass the "traffic identification" to downstream service of message consumers through the context.

**Comment by iNikem** [comment] 2021-07-19 05:41
> More often than not, the message producer will not propagate the current context information to downstream.

Can you elaborate on this statement? I believe the current understanding of OpenTelemetry, implemented in many instrumentations already, is that PRODUCER spans' context can and should be propagated together with the message.

**Comment by zmapleshine** [comment] 2021-07-19 05:57
> Can you elaborate on this statement?

Suppose a scenario where an order is created, but the order is not paid. 
For an e-commerce system, a message with a specific topic will be sent to the MQ server after the order is created, so that follow-up processing such as "close the order" can be done after the timeout. But the process is usually very long, ranging from a few minutes to a dozen minutes. Scenarios such as "auto confirm order" have even longer timeouts. For the whole trace, we do not want the intermediate waiting time to be counted in the whole trace duration.

**Comment by iNikem** [comment] 2021-07-19 06:04
Ok, so it is your use-case requirement/wish, not exactly technology specific. Because other customers did want context propagation through messaging system.

E.g. Kafka instrumentations have `otel.instrumentation.kafka.client-propagation.enabled` property to switch off context propagation either on producer or consumer side during runtime. Similar properties can be added for other messaging systems.

**Comment by zmapleshine** [comment] 2021-07-19 06:15
Yeah, that's what I mean, and you'll see that rocketmq instruments has this controlled.
https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/f5ce4c03f8d5aba5d4d4891dc6a61e368f6075bd/instrumentation/rocketmq-client-4.8/library/src/main/java/io/opentelemetry/instrumentation/rocketmq/TracingSendMessageHookImpl.java#L36

But, I found the instrumentation module USES unified instrumenter way to fold these generic instrument methods is a trend, but it is not suitable instrumenter class for mq.

**Comment by zmapleshine** [comment] 2021-08-28 09:21
@mateuszrzeszutek I reviewed the referenced code, and this control will be used when building the instrumenter.Is it possible to make control of context propagation dynamic?

**Comment by mateuszrzeszutek** [comment] 2021-08-30 10:05
Hmm, what do you mean by "dynamic"? `Config` values changing during the runtime, or figuring out whether to propagate based on the request/message?

**Comment by zmapleshine** [comment] 2021-08-31 02:21
> `Config` values changing during the runtime, or figuring out whether to propagate based on the request/message?

I think this is awkward because the `Config` class holds properties that are not modifiable and are only assigned at initialization. I think such a feature prevents control of any component that could have run time control.The current version also does not support any runtime change features.

**Comment by mateuszrzeszutek** [comment] 2021-08-31 06:11
> `Config` class holds properties that are not modifiable and are only assigned at initialization. I think such a feature prevents control of any component that could have runtime control.The current version also does not support any runtime change features.

Yeah, that was exactly my point - it's not possible to have dynamically changing `Config` values in the javaagent, it was designed with the configuration immutability in mind.

So, to reiterate: what kind of "dynamic" context propagation do you have in mind? Is it dynamically changing config (the agent doesn't support that and we don't really plan on introducing that feature), or is it deciding based on the incoming message? Or something entirely different?

**Comment by zmapleshine** [comment] 2021-08-31 06:34
> So, to reiterate: what kind of "dynamic" context propagation do you have in mind? Is it dynamically changing config (the agent doesn't support that and we don't really plan on introducing that feature), or is it deciding based on the incoming message? Or something entirely different?

Umm…I think configurability would be better if you decided to propagate based on the message

**Comment by anuraaga** [comment] 2021-08-31 09:09
I haven't really heard of sometimes propagating or sometimes not - is there something specific about messaging that you would do this?

It would be possible to implement a custom propagator and use something in the context to achieve this sort of behavior I think. It doesn't seem like something we can generalize to instrumentation from the top of my head, if users have special needs for propagation a custom propagator is probably how to achieve it. Does that make sense?

**Comment by zmapleshine** [comment] 2021-09-01 03:47
> I haven't really heard of sometimes propagating or sometimes not - is there something specific about messaging that you would do this?
> 

Hey @anuraaga ,have you ever heard full-link pressure test?  Its operating mechanism works in a production environment. This is widely used in traffic assessment, performance analysis and other scenarios for large Internet applications today.As the context propagates to the message-oriented middleware, we need to rely on an identifier (called a shadow label in our business scenario) to let storage-related logic in application determine whether traffic needs to be routed to the shadow db or mq.

**Comment by anuraaga** [comment] 2021-09-01 03:59
@zmapleshine Do you have any examples of instrumentation that currently lives today (for example based on Brave or OpenTracing) that supports this use case? It would be a good reference.

Though it still sounds like a specific use case that could be solved by a custom propagator. Does that sound like it wouldn't work?

**Comment by zmapleshine** [comment] 2021-09-01 04:34
@anuraaga I'm sorry that I can't provide the relevant instrument components for source code control reasons, because although the mechanism is consistent, the specific implementation is decided by each company.

In summary, each storage class component and messaging middleware needs to customize their instrumentation to get context information and determine whether there contain shadow markers. I think the custom propagator you mentioned can solve the logic related to message transmission. Since it is not universal, I understand that it should be independent of existing instruments. Thank you for sharing your views.

**Comment by trask** [comment] 2021-09-28 00:01
@zmapleshine were you able to find the OpenTelemetry SDK hooks needed to implement what you need?

**Comment by zmapleshine** [comment] 2021-09-29 06:34
>  were you able to find the OpenTelemetry SDK hooks needed to implement what you need?

Yes, it looks like customing ContextPropagators will solve it ~

**Comment by trask** [comment] 2021-09-29 17:49
awesome, closing, but let us know if you are still having the issue and we will re-open

**Closed by trask** 2021-09-29 17:49 UTC
Labels: enhancement
