### ISSUE TITLE
ThreadPoolExecutor.execute() or Thread.start() will create a new trace

### ISSUE THREAD

**Issue by soulmate1314** [open-telemetry/opentelemetry-java-instrumentation#8079] opened 2023-03-18 06:48 UTC
###environment Description
instrument version：1.4.1
###Bug recurrence process
`@Service
public class AServiceImpl implements IAService {

    private ExecutorService executorService = new ThreadPoolExecutor(2, 5,
            0L, TimeUnit.MILLISECONDS,
            new LinkedBlockingQueue<Runnable>(1024), new ThreadFactoryBuilder()
            .setNameFormat("yansir-pool-%d").build(), new ThreadPoolExecutor.AbortPolicy());

    @Override
    public String asend(Integer id) {
        //Thread.start() will create a new trace
        new Thread(new ConsumeRunable(id)).start();

        //Thread.run() will continue the old trace,
//        new Thread(new ConsumeRunable(id)).run();
        //ThreadPoolExecutor.execute() will continue the old trace,
        executorService.execute(new ConsumeRunable(id));
        return null;
    }

    private class ConsumeRunable implements Runnable{
        private int id;
        public ConsumeRunable(int id) {
            this.id = id;
        }
        @Override
        public void run() {
            OkHttpUtil.httpGet("http://127.0.0.1:9003/b/breceive?id="+id);
        }
    }
}`

**Comment by laurit** [comment] 2023-03-22 06:55
Duplicate of https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/8082

**Closed by laurit** 2023-03-22 06:55 UTC
Labels: bug
