### ISSUE TITLE
Support third-party metrics exporter configuration

### ISSUE THREAD

**Issue by jkwatson** [open-telemetry/opentelemetry-java-instrumentation#394] opened 2020-05-08 20:11 UTC
Like we have for span exporter configuration.

This (I think) requires this to be released by the java project:  https://github.com/open-telemetry/opentelemetry-java/pull/1180

**Comment by trask** [comment] 2020-06-16 00:58
Closing, this looks like duplicate of #475, which is done now 👍

**Closed by trask** 2020-06-16 00:58 UTC
Labels: help wanted, specification
