### ISSUE TITLE
LettuceArgSplitter#splitArgs  high cpu usage

### ISSUE THREAD

**Issue by XiaoWeiKIN** [open-telemetry/opentelemetry-java-instrumentation#8907] opened 2023-07-10 02:22 UTC
version : 1.16
jdk: 8
![image](https://github.com/open-telemetry/opentelemetry-java-instrumentation/assets/20626345/0f907fb6-ef9f-4c44-9428-97deb6b67fb7)

**Comment by breedx-splk** [comment] 2023-07-11 23:49
That regex in the impl looks to be pretty high touch. Do we know if the args wrapped with angle brackets like `key<something>` or `value<whatever>` can contain spaces? If not, it might be cheaper to split on spaces _first_ and then do pure stripping with indexes.

**Comment by XiaoWeiKIN** [comment] 2023-07-12 01:30
can i closed `spitArgs`?

**Comment by trask** [comment] 2023-07-12 02:05
> can i closed `spitArgs`?

can you elaborate, I didn't follow your question, thx!

**Comment by laurit** [comment] 2023-07-12 07:36
@XiaoWeiKIN  Based on just the screenshot it is difficult to asses how expensive exactly this regex is. It would help if you could provide a sample app that reproduces this issue or a sample input for which you believe the regex performs particularly bad. Or perhaps the issue is that this regex gets called a lot?
@breedx-splk I believe it can. It should include all that you can pass on this line https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/7e4c0fd615783c9f4d10a1706362616bacaaef65/instrumentation/lettuce/lettuce-5.1/testing/src/main/groovy/io/opentelemetry/instrumentation/lettuce/v5_1/AbstractLettuceSyncClientTest.groovy#L71 So if you add `>` in the middle of the key you'll probably get an incorrect answer back from the regex.
What we could do is that since lettuce 6 https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/7e4c0fd615783c9f4d10a1706362616bacaaef65/instrumentation/lettuce/lettuce-5.1/library/src/main/java/io/opentelemetry/instrumentation/lettuce/v5_1/OpenTelemetryTracing.java#L213-L218 we have access to the `RedisCommand` from which we can get `CommandArgs` from which we can extract the arguments without regex.

**Comment by breedx-splk** [comment] 2023-07-12 17:23
> What we could do is that since lettuce 6

Ironically, I thought I saw that we did something similar in an older version as well? Maybe I'm mis-remembering.

**Comment by laurit** [comment] 2023-07-13 08:35
@XiaoWeiKIN we have changed how the arguments are handled for lettuce 6 in https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/tag/v1.28.0 Please let us know whether this helps.

**Comment by XiaoWeiKIN** [comment] 2023-07-17 01:35
ok，I'll check it out @laurit

**Comment by XiaoWeiKIN** [comment] 2023-07-19 01:46
hi,@laurit. I have updated the agent version to` 1.28.0`, but now lettuce instrument still has a high cpu load. from the flame diagram, I can see that lettue inst still occupies 16% cpu，mostly `ValueArgument.tostring` method. I am wondering is there any way to disable `db.stament`?

![image](https://github.com/open-telemetry/opentelemetry-java-instrumentation/assets/20626345/5594bec4-92ae-4b03-95a7-02356a28780e)

**Comment by breedx-splk** [comment] 2023-07-19 21:15
>  I am wondering is there any way to disable db.stament [sic]?

I don't think this exists yet, but seems like a reasonable request. It might conflict with the spec, though. I have tried to provide a little optimization in #8984 up there. 🤞🏻

**Comment by laurit** [comment] 2023-08-09 12:38
Resolved in https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/8984

**Closed by laurit** 2023-08-09 12:38 UTC
Labels: bug
