### ISSUE TITLE
Remove gRPC from slim javaagent

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-instrumentation#4415] opened 2021-10-18 17:22 UTC
This should be possible now due to https://github.com/open-telemetry/opentelemetry-java/pull/3684, and should reduce slim javaagent jar file by a nice 4mb.

**Comment by ryanrupp** [comment] 2022-01-05 06:00
Was this resolved by https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/4674? Was upgrading the agent and was just trying to see which changes moved requests from gRPC Netty --> OkHttp and found that PR and also this issue. Also looks like the PR change applies to both the regular and slim artifacts - think that was intended but I was just trying to understand the if there's any repercussions to consider there. Seemed like the gist of the linked issue is that gRPC java as a dependency is overkill for the serialization side of things so just skip and and use OkHttp directly. So I guess the only risk there is just a less tested code path possibly but this does ship as the default now for the agent.

**Comment by anuraaga** [comment] 2022-01-05 06:04
Thanks @ryanrupp - indeed this was resolved by that PR. We originally were targeting slim with exporters like the jaeger one still using the heavyweight gRPC dependency at the time. All of that was cleaned up in the SDK though and we decided to remove from both. Your analysis `Seemed like the gist of the linked issue is that gRPC java as a dependency is overkill for the serialization side of things so just skip and and use OkHttp directly. So I guess the only risk there is just a less tested code path possibly but this does ship as the default now for the agent.` is spot-on, and hopefully by now it's been tested more since the 1.9.0 was first released.

**Closed by anuraaga** 2022-01-05 06:04 UTC
Labels: enhancement
