### ISSUE TITLE
Thread.start() will create a new trace

### ISSUE THREAD

**Issue by soulmate1314** [open-telemetry/opentelemetry-java-instrumentation#8082] opened 2023-03-18 12:56 UTC
###environment Description
instrument version：1.4.1
###Bug Description
when use Thread.start() ,the OkHttpUtil.httpGet('url') span will be a new trace ,not in the old trace.
###Bug recurrence process

    private ExecutorService executorService = new ThreadPoolExecutor(2, 5,
            0L, TimeUnit.MILLISECONDS,
            new LinkedBlockingQueue<Runnable>(1024), new ThreadFactoryBuilder()
            .setNameFormat("yansir-pool-%d").build(), new ThreadPoolExecutor.AbortPolicy());
        //Thread.start() will create a new trace
        new Thread(new ConsumeRunable(id)).start();

        //Thread.run() will continue the old trace,
        new Thread(new ConsumeRunable(id)).run();
        //ThreadPoolExecutor.execute() will continue the old trace,
        executorService.execute(new ConsumeRunable(id));

    private class ConsumeRunable implements Runnable{
        private int id;
        public ConsumeRunable(int id) {
            this.id = id;
        }
        @Override
        public void run() {
            OkHttpUtil.httpGet("http://127.0.0.1:9003/b/breceive?id="+id);
        }
    }

**Comment by laurit** [comment] 2023-03-22 06:54
Duplicate of https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/2527
Propagating context into threads started with `Thread.start()` is not implemented yet.

**Closed** 2023-03-23 13:04 UTC
Labels: bug
