### ISSUE TITLE
Timestamps inside the -all.jar are all 02-01-1980

### ISSUE THREAD

**Issue by breedx-splk** [open-telemetry/opentelemetry-java-instrumentation#2517] opened 2021-03-05 17:20 UTC
Follow-up issue from #2459 

Timestamps of all the files inside the jar are all 02-01-1980.
```
Archive:  opentelemetry-javaagent-0.17.0-all.jar
  Length      Date    Time    Name
---------  ---------- -----   ----
        0  02-01-1980 00:00   META-INF/
      461  02-01-1980 00:00   META-INF/MANIFEST.MF
        0  02-01-1980 00:00   META-INF/licenses/
    39254  02-01-1980 00:00   META-INF/licenses/licenses.md
        0  02-01-1980 00:00   META-INF/licenses/byte-buddy-1.10.18.jar/
        0  02-01-1980 00:00   META-INF/licenses/byte-buddy-1.10.18.jar/META-INF/
    10301  02-01-1980 00:00   META-INF/licenses/byte-buddy-1.10.18.jar/META-INF/LICENSE
      567  02-01-1980 00:00   META-INF/licenses/byte-buddy-1.10.18.jar/META-INF/NOTICE
        0  02-01-1980 00:00   META-INF/licenses/byte-buddy-agent-1.10.18.jar/
        0  02-01-1980 00:00   META-INF/licenses/byte-buddy-agent-1.10.18.jar/META-INF/
    10140  02-01-1980 00:00   META-INF/licenses/byte-buddy-agent-1.10.18.jar/META-INF/LICENSE
      567  02-01-1980 00:00   META-INF/licenses/byte-buddy-agent-1.10.18.jar/META-INF/NOTICE
<etc>
```

This is odd and misleading, and people sometimes want to actually know/verify times of certain files.

Ideally, even when being shaded, the files would retain their original timestamps.

**Comment by laurit** [comment] 2021-03-08 10:16
I believe that this is done to make builds reproducible. Removing
```
tasks.withType(AbstractArchiveTask) {
  preserveFileTimestamps = false
  reproducibleFileOrder = true
}
```
from `gradle/java.gradle` might get the timestamps back.

**Comment by iNikem** [comment] 2021-03-08 13:12
`reproducibleFileOrder` is certainly desirable. And I don't think we should remove `preserveFileTimestamps` as well. But if we do, then we have to make sure this does not break Gradle build cache.

**Comment by breedx-splk** [comment] 2021-03-08 17:00
What about settings `preserveFileTimestamps = true` instead of removing it? Isn't that what we want?

**Comment by breedx-splk** [comment] 2021-03-11 23:06
> > What about settings `preserveFileTimestamps = true` instead of removing it? Isn't that what we want?
> 
> These two options are equivalent, aren't they?

I dunno, but it's it better to be explicit here rather than requiring the reader to know how gradle might have chosen to implement an obscure default?

**Comment by iNikem** [comment] 2021-09-20 16:19
@open-telemetry/java-approvers @breedx-splk do we still think of this issue as important? I am tempted to close it.

**Comment by breedx-splk** [comment] 2021-09-20 18:19
```
$ curl -qsL https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/download/v1.6.0/opentelemetry-javaagent-all.jar | jar tv | head
     0 Fri Feb 01 00:00:00 PST 1980 META-INF/
   460 Fri Feb 01 00:00:00 PST 1980 META-INF/MANIFEST.MF
     0 Fri Feb 01 00:00:00 PST 1980 io/
     0 Fri Feb 01 00:00:00 PST 1980 io/opentelemetry/
     0 Fri Feb 01 00:00:00 PST 1980 io/opentelemetry/javaagent/
     0 Fri Feb 01 00:00:00 PST 1980 io/opentelemetry/javaagent/shaded/
     0 Fri Feb 01 00:00:00 PST 1980 io/opentelemetry/javaagent/shaded/instrumentation/
     0 Fri Feb 01 00:00:00 PST 1980 io/opentelemetry/javaagent/shaded/instrumentation/api/
[...]
```

It's still an issue. As far as relative priority, probably not high. But incorrect. Closing this will increase the likelihood of it never getting fixed.

**Comment by iNikem** [comment] 2021-09-20 19:18
Why is this an issue? why files timestamps inside jar are important?

**Comment by breedx-splk** [comment] 2021-09-20 21:43
Same reason that filesystems have timestamps...it indicates when a file was last modified. Same reasons I gave in the original issue description. I've needed to dissect jar contents before, and when the timestamps are all broken it makes it that much harder to compare inputs and outputs. 

I think it's also just a bad look that weakens confidence in the build process being good. I dunno. I'll close since I seem to be the only one that cares...if one other person out there cares, then we can reopen.

**Comment by trask** [comment] 2021-09-20 23:43
> I think it's also just a bad look that weakens confidence in the build process being good

👍

> if one other person out there cares, then we can reopen

(re-opening)

**Comment by iNikem** [comment] 2021-09-21 04:47
> > I think it's also just a bad look that weakens confidence in the build process being good
> 
> 👍
> 

I don't understand this argument :) E.g. `jib` also by default creates image with timestamp equal to start of the epoch. For the same reason: build reproducibility. I don't understand how this means "bad build process" :)

**Comment by trask** [comment] 2021-09-21 21:28
setting timestamp equal to start of the epoch may be a common practice for docker images, but I haven't seen that before for jar files, which is why it looks unusual in the javaagent jar

**Comment by trask** [comment] 2022-06-26 05:10
maybe we don't want to fix this after all due to #6071? what do u think @hboutemy?

**Comment by breedx-splk** [comment] 2022-06-30 15:54
@trask #6071 only addressed the file permissions, right? And not the timestamps. The original intent of this issue here was somewhat less about reproducibility and more about not losing metadata. If I'm the only one who finds it valuable to be able to look inside the jar and see that we're using a version of a library from 2022 vs. 2018 (and not just defaulted to 1970, heh)...then I'm ok closing it.

It still seems odd to me tho. Why lose that metadata at all?

**Comment by trask** [comment] 2022-06-30 18:01
> @trask #6071 only addressed the file permissions, right? And not the timestamps.

I'm wondering if we fix this issue, will we break build reproducibility?

> If I'm the only one who finds it valuable to be able to look inside the jar and see that we're using a version of a library from 2022 vs. 2018 (and not just defaulted to 1980, heh)...then I'm ok closing it.

I also find this odd, I'm curious what other Java libraries are doing, and if this oddness is worth build reproducibility.

@hboutemy would love your thoughts

**Comment by cowtowncoder** [comment] 2022-11-23 04:21
Found this by googling: Jackson project has same issue (https://github.com/FasterXML/jackson-databind/issues/3680).
Not necessarily a big problem but annoying cosmetic problem. As far as I understand things, given timestamp (updated as part of release process) should be used for class files, but instead only appears to be used for metadata under `META-INF`.

Also wondering what happened to  @hboutemy who submitted original change to enable reproducible builds?

**Comment by hboutemy** [comment] 2022-11-24 07:10
@trask sorry, I completely overlooked your questions

we need to share a few logical steps:
1. defining a reproducible timestamp is required by Reproducible Builds (whatever the value will be)

2. at Maven level, I chose to make the timestamp value configurable: that's the purpose of `project.build.outputTimestamp`, that inherently has multiple strategies for users to update the value if they want a value that changes over time (to match a semantic that was until now informal): see first FAQ topic in https://maven.apache.org/guides/mini/guide-reproducible-builds.html#faq

3. at Gradle level, it seems they chose to make things simpler for users: reproducibility is a boolean, timestamp value is fully chosen by Gradle, apparently with the only algorithm that I can find that works in any situation = use a static value (I also heard that this value may represent a "no timestamp" semantic for zip file format, but I could not find any pointer to any zip format documentation which is explicit about this semantic). Gradle documentation is here https://docs.gradle.org/current/userguide/working_with_files.html#sec:reproducible_archives

> I also find this odd, I'm curious what other Java libraries are doing, and if this oddness is worth build reproducibility.

the key choice done by java libraries is their build tool: the way Reproducible Builds is implemented is defined at build tool level for now https://reproducible-builds.org/docs/jvm/

**Comment by breedx-splk** [comment] 2022-11-28 17:09
Thanks @trask and @hboutemy and others. I really hadn't given much thought to the impact on reproducibility when opening this issue. It's a bit of a can of worms I guess....

If I could wave a magic wand, here's what I think would be awesome:

* All items shaded from dependencies would preserve their original timestamps. For archives, it's assumed that each file inside the archive has a timestamp that carries forward.
* All items checked into the repository preserve their timestamps 
* All _generated_ items (compiler output, metadata) are timestamped with the most recent git commit timestamp.

For most projects, I think that would check the boxes for ✅ consistency for troubleshooting/forensics, ✅ reproducibility, and ✅ least surprise.

Maybe it's more work than it's worth.

**Comment by hboutemy** [comment] 2022-12-03 14:44
@breedx-splk on shaded dependencies, this is how I implemented it https://issues.apache.org/jira/browse/MSHADE-347

here is the global logic I did https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=74682318

if you want to update anything, don't hesitate

**Comment by trask** [comment] 2024-12-22 05:08
Closing based on https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/2517#issuecomment-2396028993

**Closed by trask** 2024-12-22 05:08 UTC
Labels: bug, contribution welcome
