### ISSUE TITLE
NullPointerException from AWS SDK SQS instrumentation masks real exception

### ISSUE THREAD

**Issue by hannahchan** [open-telemetry/opentelemetry-java-instrumentation#10270] opened 2024-01-18 04:25 UTC
### Describe the bug

When running the OpenTelemetry Java agent with the AWS SDK instrumentation enabled, when trying to send a message to a SQS queue we don't have permission for, we get a `NullPointerException` that masks or prevents the real underlying exception from being surfaced.

This misleads investigations towards a root cause.

This is the exception that we received;

```
Caused by: java.lang.NullPointerException
    at io.opentelemetry.javaagent.shaded.instrumentation.awssdk.v1_11.SqsImpl.getMessageId(SqsImpl.java:140)
    at io.opentelemetry.javaagent.shaded.instrumentation.awssdk.v1_11.SqsAccess.getMessageId(SqsAccess.java:43)
    at io.opentelemetry.javaagent.shaded.instrumentation.awssdk.v1_11.SqsAttributesGetter.getMessageId(SqsAttributesGetter.java:57)
    at io.opentelemetry.javaagent.shaded.instrumentation.awssdk.v1_11.SqsAttributesGetter.getMessageId(SqsAttributesGetter.java:15)
    at io.opentelemetry.javaagent.shaded.instrumentation.api.instrumenter.messaging.MessagingAttributesExtractor.onEnd(MessagingAttributesExtractor.java:107)
    at io.opentelemetry.javaagent.shaded.instrumentation.api.instrumenter.Instrumenter.doEnd(Instrumenter.java:226)
    at io.opentelemetry.javaagent.shaded.instrumentation.api.instrumenter.Instrumenter.end(Instrumenter.java:146)
    at io.opentelemetry.javaagent.shaded.instrumentation.awssdk.v1_11.TracingRequestHandler.finish(TracingRequestHandler.java:156)
    at io.opentelemetry.javaagent.shaded.instrumentation.awssdk.v1_11.TracingRequestHandler.afterError(TracingRequestHandler.java:127)
    at io.opentelemetry.javaagent.instrumentation.awssdk.v1_11.TracingRequestHandler.afterError(TracingRequestHandler.java:70)
    at com.amazonaws.http.AmazonHttpClient$RequestExecutor.afterError(AmazonHttpClient.java:1063)
    at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:825)
    at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:781)
    at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:755)
    at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:715)
    at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:697)
    at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:561)
    at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:541)
    at com.amazonaws.services.sqs.AmazonSQSClient.doInvoke(AmazonSQSClient.java:2554)
    at com.amazonaws.services.sqs.AmazonSQSClient.invoke(AmazonSQSClient.java:2521)
    at com.amazonaws.services.sqs.AmazonSQSClient.invoke(AmazonSQSClient.java:2510)
    at com.amazonaws.services.sqs.AmazonSQSClient.executeSendMessage(AmazonSQSClient.java:2017)
    at com.amazonaws.services.sqs.AmazonSQSClient.sendMessage(AmazonSQSClient.java:1986)
    ...
```

This is the exception that we expected / received when we disable the Java agent/instrumentation.

```
Caused by: com.amazonaws.services.sqs.model.AmazonSQSException: User: arn:aws:sts::-:assumed-role/-/- is not authorized to perform: sqs:sendmessage on resource: arn:aws:sqs:us-east-1:-:- because no resource-based policy allows the sqs:sendmessage action (Service: AmazonSQS; Status Code: 403; Error Code: AccessDenied; Request ID: -; Proxy: null)
```

### Steps to reproduce

Send a message using the AWS SDK client with SQS instrumentation enabled to an SQS queue without the correct permissions.

### Expected behavior

No `NullPointerException` is thrown. 

### Actual behavior

A `NullPointerException` is thrown from the instrumentation code which confuses and misleads engineers about the root cause.

### Javaagent or library instrumentation version

1.32.0

### Environment

**JDK**:
**OS**:

**Comment by laurit** [comment] 2024-01-18 09:18
Duplicate of https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/10029

**Closed by laurit** 2024-01-18 09:18 UTC
Labels: bug, needs triage
