### ISSUE TITLE
Internal span name is being overridden by opentelemetry-javaagent

### ISSUE THREAD

**Issue by shaykeren** [open-telemetry/opentelemetry-java-instrumentation#10278] opened 2024-01-18 12:50 UTC
### Describe the bug

using spring-petclinic application and run testInitCreationForm test (WebMvcTest)  I found out that the span name I created in the test was overridden with the name "GET /owners/new"

Running WebMvcTest test using the following configuration:
JAVA_TOOL_OPTIONS:  -javaagent:/opentelemetry-javaagent.jar 
-Dotel.exporter.otlp.traces.endpoint=ObservabilityURL
-Dotel.javaagent.experimental.field-injection.enabled=false 
-Dotel.traces.exporter=otlp 
-Dotel.metrics.exporter=none 
-Dotel.instrumentation.experimental.span-suppression-strategy=none 
-Dotel.service.name=spring-petclinic 

using opentelemetry-javaagent - version: 1.32.0

### Steps to reproduce

1. use spring-petclinic repository
2. modify test name "testInitCreationForm" and add **@WithSpan()** annotation
```
@WithSpan()
@Test
void testInitCreationForm() throws Exception {
       mockMvc.perform(get("/owners/new"))
	.andExpect(status().isOk())
	.andExpect(model().attributeExists("owner"))
	.andExpect(view().name("owners/createOrUpdateOwnerForm"));
}

```
3. run test  with the following configuration:
 test using the following configuration:
JAVA_TOOL_OPTIONS:  -javaagent:/opentelemetry-javaagent.jar 
-Dotel.exporter.otlp.traces.endpoint=ObservabilityURL
-Dotel.javaagent.experimental.field-injection.enabled=false 
-Dotel.traces.exporter=otlp 
-Dotel.metrics.exporter=none 
-Dotel.instrumentation.experimental.span-suppression-strategy=none 
-Dotel.service.name=spring-petclinic 

And observe the following trace:
the span name was overridden with the name "GET /owners/new"
![image](https://github.com/open-telemetry/opentelemetry-java-instrumentation/assets/1392692/b0d7d59a-eb08-4a70-832b-a9afd5e5e651)

### Expected behavior

my span name should not be changed

### Actual behavior

span name changed to: GET /owners/new

### Javaagent or library instrumentation version

1.32.0

### Environment

:: Built with Spring Boot :: 3.2.0
Java 17.0.7
macos

**Comment by laurit** [comment] 2024-01-18 16:10
My guess is that the issue is in
https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/9e208c85740dfa5035c29ba84a419ff94b9ee519/instrumentation-api/src/main/java/io/opentelemetry/instrumentation/api/semconv/http/HttpServerRoute.java#L100
we update the name on the root span regardless of whether it is a server or internal span. I guess we could change it to update only server spans.

**Comment by doppleware** [comment] 2024-02-05 00:27
Hey guys anything we can do to help with this one?

**Comment by trask** [comment] 2024-02-06 02:10
@laurit submitted a fix for this already (linked above). If you are able to build a snapshot from the PR branch and verify it resolves your issue that could be helpful.

**Closed** 2024-02-14 07:25 UTC
Labels: bug, needs triage

**Comment by doppleware** [comment] 2024-02-14 23:05
Hey - I can confirm this works, thank you :) Is it possible to merge it to a stable release as well on the next minor/patch?
