### ISSUE TITLE
Usage of ...Advice.class.getName() vs string constants

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-instrumentation#1571] opened 2020-11-06 06:22 UTC
It's not obvious why we use string constants instead of `...Advice.class.getName()`, e.g. when building transformers() map.

I suspect it's an optimization to avoid loading the Advice class into the AgentClassLoader.

If we want to keep this optimization, it would be good to add a checkstyle rule for it to add to avoid drift over time.

**Comment by iNikem** [comment] 2020-11-06 06:37
I would LOVE to know the answer to this. @tylerbenson ?

**Comment by mateuszrzeszutek** [comment] 2020-11-06 10:02
When I was refactoring all `Instrumenter`s I've noticed a comment saying that `...Advice.class.getName()` won't work on Java 7 - maybe that was part of the cause.

**Comment by devinsba** [comment] 2020-11-06 15:15
What @trask says is the main reason for the strings. If the advice classes are loaded as is, not only does it load that class, it loads all the Bytebuddy annotation classes, and a bunch of supporting classes.

**Comment by tylerbenson** [comment] 2020-11-06 15:16
yeah, it's a combination of not loading a class unnecessarily, but also some of our advice is compiled against a class version that may not be supported (ie java 11's http client). (The last part was more significant when we supported java 7.)

**Comment by vovencij** [comment] 2020-11-06 17:21
Would be nice to have this knowledge documented somewhere in addition to checkstyle rule.

**Comment by mateuszrzeszutek** [comment] 2021-04-15 14:53
This is now documented in https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/docs/contributing/writing-instrumentation-module.md#transformers
I think we can close this issue.

**Closed by mateuszrzeszutek** 2021-04-15 14:53 UTC
Labels: discussion, release:after-ga
